spring:
  application:
    name: auth-microservice
server:
  port: 8083
  eureka:
    instance:
      hostname: localhost
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/fulandt?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&sslMode=DISABLED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fulandt




